[general]
import = [
    "~/.config/alacritty/themes/nordfox.toml"
]
[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[terminal]
shell = { program = "/usr/bin/env", args = ["fish", "--login", "--interactive"] }

[window]
# Mac....
option_as_alt = 'Both'
