#!/usr/bin/env zsh

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    STOW_FOLDERS="alacritty,fish,git,i3,kitty,nvim,qtile,rofi,starship,tmux,zsh"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    STOW_FOLDERS="alacritty,fish,git,kitty,nvim,starship,tmux,zsh"
else
    echo "unknown os type"
    exit 2
fi

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done
popd

