theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "multiple"
auto-format = true

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[keys.normal]
H = "goto_line_start"
L = "goto_line_end"

[keys.select]
H = "goto_line_start"
L = "goto_line_end"

[keys.insert]
"C-space" = "completion"
