[[language]]
name = "go"
file-types = ["go", "go.mod"]

[[language]]
name = "rust"
config = {checkOnSave = {command = "clippy"}}

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true