# Don't print a new line at the start of the prompt
add_newline = false
#single line
[line_break]
disabled = false

[gcloud]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
disabled = true
# success_symbol = "[➜](bold green)"
# error_symbol = "[➜](bold red)"
# vicmd_symbol = "[V](bold green)"
