# Don't print a new line at the start of the prompt
add_newline = false
#single line
[line_break]
disabled = false

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vicmd_symbol = "[V](bold green)"
