# Don't print a new line at the start of the prompt
add_newline = false
#single line
[line_break]
disabled = true

[gcloud]
disabled = true

[cmd_duration]
disabled = true

[java]
disabled = true

[package]
disabled = true
